### PR TITLE
added dark mode to sidebar

### PR DESCRIPTION
**Pull request by Kronicom**
Another small tweak.

### CODE REVIEW

**Comment by Kronicom** [comment]
Yeah ok I'll take care of that

**Comment by smakosh** [comment]
The only needed change ☝️

**Comment by Kronicom** [comment]
Oh yes but I don't think we can do that. FYI I'm not very good with svg's. 
If we use "prefers-color-scheme: dark" it does the trick but it stays white, that media query doesn't allow other media query's nestings.


example: 
`<style type="text/css">
	@media only screen (prefers-color-scheme: dark) {
    	  circle  {
    	    fill: white;
            stroke: white;
    	  }
	 line {
	    stroke: white;
          }
	}
</style>`

**Comment by smakosh** [comment]
You can convert the svg icons to React components and pass the color as a prop

**Comment by smakosh** [comment]
> You can convert the svg icons to a React component and pass the color as a prop

you don't even have to go with this as when ever it's dark it's the sun icon showing, so you can just update its color on the svg file

**Pull request merged**
