### PR TITLE
Feature: Add programming languages to 'Projects'

### PR DESCRIPTION
**Pull request by benji011**
## What

In https://portfolio.smakosh.com we have below:

### Before
image

### After
image

## Why

I forked from this repo & added these changes and then figured this might be a cool thing to add here. If this is ok (or if it's not really needed) please let me know. Thanks!

### CODE REVIEW

**Comment by smakosh** [comment]
Hey @benji011 this looks cool actually, worried how it would look like when there are many, could you think of a way to handle the UI on that case?

**Comment by benji011** [comment]
Hi @smakosh ! I thought about that so I set the condition to be `languages: first 3`. In the case it's none an empty string is returned. 

I think setting just 1 may infact even be enough. Is this what you mean?

**Comment by smakosh** [comment]
> Hi @smakosh ! I thought about that so I set the condition to be `languages: first 3`. In the case it's none an empty string is returned. 
> 
> I think setting just 1 may infact even be enough. Is this what you mean?

Yup, correct! Let me review your code real quick

**Review by smakosh — APPROVED** [review]
LGTM, thanks for the contribution @benji011 🚀

**Pull request merged**
